language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=Django==1.3.7
  - DJANGO=Django==1.4.9
  - DJANGO=Django==1.5.5
  - DJANGO=Django==1.6.2
  - DJANGO=https://github.com/django/django/archive/master.zip
matrix:
  include:
    - python: "3.3"
      env: DJANGO=Django==1.5.5
    - python: "3.3"
      env: DJANGO=Django==1.6.2
    - python: "3.3"
      env: DJANGO=https://github.com/django/django/archive/master.zip
  exclude:
    - python: "2.6"
      env: DJANGO=https://github.com/django/django/archive/master.zip
install:
  - pip install south
  - pip install $DJANGO
  - pip install -e .
script:
  - ./runtests.sh
